name: Hprofile Actions

on:
  push:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 3. Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      # 4. Run Maven Tests
      - name: Maven Test
        run: mvn test

      # 5. Run Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      # 6. Setup SonarQube
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # 7. Verify Secrets (Optional but Recommended)
      - name: Verify SonarQube Secrets
        run: |
          if [ -z "${{ secrets.SONAR_URL }}" ]; then echo "SONAR_URL is not set"; else echo "SONAR_URL is set"; fi
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then echo "SONAR_TOKEN is not set"; else echo "SONAR_TOKEN is set"; fi
          if [ -z "${{ secrets.SONAR_ORGANIZATION }}" ]; then echo "SONAR_ORGANIZATION is not set"; else echo "SONAR_ORGANIZATION is set"; fi
          if [ -z "${{ secrets.SONAR_PROJECT_KEY }}" ]; then echo "SONAR_PROJECT_KEY is not set"; else echo "SONAR_PROJECT_KEY is set"; fi

      # 8. SonarQube Scan
      - name: SonarQube Scan
        run: |
          sonar-scanner -X \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/classes
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.12-7.1/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.12-7.1/x64
